name: CI

on: push

jobs:
  lint:
    name: Lint 🚨
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - name: Install Ruby 💎
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
      - name: Install dependencies 📦
        run: |
          echo 'gem: --no-document' >> ~/.gemrc
          gem install standardrb
      - name: Run linter 🚨
        run: standardrb
  test:
    name: Test 🧪
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 3.3
          - 3.2
          - 3.1
          - 3.0
          - 2.7
    env:
      BUNDLE_GEMFILE: Gemfile
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - name: Install Ruby 💎
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Install dependencies 📦
        run: bundle install
      - name: Run tests 🧪
        run: bundle exec ruby -Ilib test/*.rb
